### ISSUE TITLE
Revamp add game page UI

### ISSUE THREAD

**Issue by marttsang2** [C-M-limited/frontend-gamehub#4]

**Comment by bigbigphone2** [comment]
<img width="697" alt="Screenshot 2023-10-22 at 8 53 14 PM" src="https://github.com/C-M-limited/frontend-gamehub/assets/94114579/4f1a7dce-1d71-4c77-9d53-b8455351ce70">

changed to this?

**Comment by Chris-Lee-Ca** [comment]
I am now working on this
